In [7]:
import pandas as pd
from sklearn.model_selection import StratifiedKFold
df = pd.read_csv("../data/train.csv")
X = df.drop(columns = "fav_novel_cnt_bin")
y = df[["fav_novel_cnt_bin"]]
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for train_index, test_index in skf.split(X, y):
    # print(i)
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X.iloc[train_index, :], X.iloc[test_index, :]
    y_train, y_test = y.iloc[train_index, :], y.iloc[test_index, :]

TRAIN: [    0     1     2 ... 39995 39996 39999] TEST: [   19    36    57 ... 39993 39997 39998]
TRAIN: [    0     1     2 ... 39997 39998 39999] TEST: [    3     6    10 ... 39986 39987 39990]
TRAIN: [    0     2     3 ... 39995 39997 39998] TEST: [    1     9    18 ... 39994 39996 39999]
TRAIN: [    0     1     2 ... 39997 39998 39999] TEST: [   11    16    23 ... 39981 39989 39995]
TRAIN: [    1     3     6 ... 39997 39998 39999] TEST: [    0     2     4 ... 39982 39984 39988]

In [25]:
df_0 = pd.read_csv("./output/exp7_0.csv")
df_1 = pd.read_csv("./output/exp7_1.csv")
df_2 = pd.read_csv("./output/exp7_2.csv")
df_3 = pd.read_csv("./output/exp7_3.csv")
df_4 = pd.read_csv("./output/exp7_4.csv")
pd.concat([df_0 , df_1, df_2, df_3, df_4]).groupby("ncode").mean().reset_index().to_csv("./output/sub.csv", index=False)

        ncode   proba_0   proba_1   proba_2   proba_3   proba_4
0     N0001HE  0.852866  0.138611  0.007066  0.001296  0.000161
1     N0002HE  0.144874  0.805980  0.042926  0.005957  0.000263
2     N0004HF  0.549970  0.430145  0.017645  0.001878  0.000362
3     N0005HE  0.005317  0.016975  0.264939  0.711492  0.001277
4     N0006HF  0.197087  0.542408  0.208981  0.043033  0.008490
...       ...       ...       ...       ...       ...       ...
8517  N9994HE  0.863647  0.130100  0.005139  0.000922  0.000192
8518  N9995HD  0.752319  0.232661  0.013177  0.001512  0.000331
8519  N9998HD  0.233872  0.386807  0.326319  0.051567  0.001436
8520  N9999HD  0.702919  0.275458  0.017105  0.004183  0.000336
8521  N9999HE  0.630874  0.339941  0.026582  0.002243  0.000360

[8522 rows x 6 columns]